services:
  owui:
    build:
      context: ../Dockerfiles
      dockerfile: Dockerfile.cpu
    image: kylefoxaustin/openwebui:cpu-only
    container_name: owui-cpu
    ports:
      - "8080:8080" 
      - "11436:11434"  # Map container's 11434 to host's 11436
    volumes:
      - ollama_data:/root/.ollama
      - openwebui_data:/app/backend/data
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0

volumes:
  ollama_data:
  openwebui_data:
  
