services:
  owui:
    build:
      context: ../Dockerfiles
      dockerfile: Dockerfile.gpu
    image: owui-custom:gpu
    container_name: owui-gpu
    ports:
      - "8080:8080"
      - "11436:11434"  # Map container's 11434 to host's 11436
    volumes:
      - ollama_data:/root/.ollama
      - openwebui_data:/app/backend/data
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    # GPU configuration
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ollama_data:
  openwebui_data:

